### ISSUE TITLE
crud para url de retorno dado um callback_id

### ISSUE THREAD

**Issue by thiagogomesverissimo** [wgnann/senhaunica-faker-laravel#2]
A requisição retorna para callback. Apesar de ser um padrão do oauth 1 a usp ignora o callback e retorna o a requisição com o token gerado para uma url cadastrada anteriormente para callback_id. Por isso, a biblioteca socialite senhaunica não envia callback na requisição. Para deixar mais próximo do provider real, poderíamos :

- fazer um crud para callback id
- ou mais simples, ter no .env a url default de retorno

**Comment by wgnann** [comment]
Gostei da opção de colocar a URL de `callback`. O lado ruim é que somente um projeto será testado por vez (ou teremos de subir o provider usando outra variável de ambiente).

**Comment by thiagogomesverissimo** [comment]
Para este momento está otimo só um sistema para testes, não?
