### ISSUE TITLE
Vamos combinar os fakers gerados aqui com o repliciaco faker?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [wgnann/senhaunica-faker-laravel#4]

**Comment by wgnann** [comment]
Eu não quero ter que usar replicado a partir desse sistema, pois o objetivo dele é só entregar um OAuth falso. O que ele tem de faker, digamos assim, é só o que é provido pelo `/usuariousp`.

Usar uma mesma função geradora para os dados de ambos parece uma boa ideia.

**Comment by thiagogomesverissimo** [comment]
Entendi. Mas a ideia não é acoplar não.  É só para quem usar ambos ter os mesmos fakers.  Mas posso implementar isso direto no replicado faker, é melhor na real.
