### ISSUE TITLE
instruções de como usar?

### ISSUE THREAD

**Issue by masakik** [wgnann/senhaunica-faker-laravel#9]
Alguma ajuda?

**Comment by wgnann** [comment]
Tipo no README.md?

**Comment by masakik** [comment]
isso, eu ia configurar aqui  e não sei como fazer.

**Comment by wgnann** [comment]
Vou fazer uma reinstalação para testar e já acrescento no README. Mas deveria ser algo como:
clone, composer install e mudar o parâmetro de APP_URL.

**Comment by masakik** [comment]
aí tem de subir o laravel nele isso? 
E depois para usar quando manda uma autenticação a gente pode colocar qualquer coisa no usuário e senha? ou tem as instruçoes na tela de autenticação? 
Obrigado.

**Comment by wgnann** [comment]
é. daí é só rodar o php artisan serve com os parâmetros desejados.

existe instrução na tela de autenticação sobre o que colocar no usuário / senha. segue aquela sua ideia de definir vínculo a partir do número
